### First try

In [2]:
import numpy as np
import pandas as pd
import warnings 
warnings.filterwarnings('ignore')

In [3]:
import seaborn as sns
import matplotlib.pyplot as mplt

In [28]:
from sklearn.model_selection import train_test_split

In [32]:
from sklearn.ensemble import RandomForestClassifier 

In [62]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

### Data Gather

In [4]:
df=pd.read_csv('HR_data.csv')

In [5]:
df

Age Attrition     BusinessTravel  DailyRate              Department  \
0      41       Yes      Travel_Rarely       1102                   Sales   
1      49        No  Travel_Frequently        279  Research & Development   
2      37       Yes      Travel_Rarely       1373  Research & Development   
3      33        No  Travel_Frequently       1392  Research & Development   
4      27        No      Travel_Rarely        591  Research & Development   
...   ...       ...                ...        ...                     ...   
1465   36        No  Travel_Frequently        884  Research & Development   
1466   39        No      Travel_Rarely        613  Research & Development   
1467   27        No      Travel_Rarely        155  Research & Development   
1468   49        No  Travel_Frequently       1023                   Sales   
1469   34        No      Travel_Rarely        628  Research & Development   

      DistanceFromHome  Education EducationField  EmployeeCount  \
0                    1          2  Life Sciences              1   
1                    8          1  Life Sciences              1   
2                    2          2          Other              1   
3                    3          4  Life Sciences              1   
4                    2          1        Medical              1   
...                ...        ...            ...            ...   
1465                23          2        Medical              1   
1466                 6          1        Medical              1   
1467                 4          3  Life Sciences              1   
1468                 2          3        Medical              1   
1469                 8          3        Medical              1   

      EmployeeNumber  ...  RelationshipSatisfaction StandardHours  \
0                  1  ...                         1            80   
1                  2  ...                         4            80   
2                  4  ...                         2            80   
3                  5  ...                         3            80   
4                  7  ...                         4            80   
...              ...  ...                       ...           ...   
1465            2061  ...                         3            80   
1466            2062  ...                         1            80   
1467            2064  ...                         2            80   
1468            2065  ...                         4            80   
1469            2068  ...                         1            80   

      StockOptionLevel  TotalWorkingYears  TrainingTimesLastYear  \
0                    0                  8                      0   
1                    1                 10                      3   
2                    0                  7                      3   
3                    0                  8                      3   
4                    1                  6                      3   
...                ...                ...                    ...   
1465                 1                 17                      3   
1466                 1                  9                      5   
1467                 1                  6                      0   
1468                 0                 17                      3   
1469                 0                  6                      3   

     WorkLifeBalance  YearsAtCompany YearsInCurrentRole  \
0                  1               6                  4   
1                  3              10                  7   
2                  3               0                  0   
3                  3               8                  7   
4                  3               2                  2   
...              ...             ...                ...   
1465               3               5                  2   
1466               3               7                  7   
1467               3               6                  2   
1468               2               9    

In [6]:
dropCol = ['EmployeeCount','EmployeeNumber','Over18', 'StandardHours','Attrition']

In [7]:
df1 = df.drop(dropCol, axis=1)
df1

Age     BusinessTravel  DailyRate              Department  \
0      41      Travel_Rarely       1102                   Sales   
1      49  Travel_Frequently        279  Research & Development   
2      37      Travel_Rarely       1373  Research & Development   
3      33  Travel_Frequently       1392  Research & Development   
4      27      Travel_Rarely        591  Research & Development   
...   ...                ...        ...                     ...   
1465   36  Travel_Frequently        884  Research & Development   
1466   39      Travel_Rarely        613  Research & Development   
1467   27      Travel_Rarely        155  Research & Development   
1468   49  Travel_Frequently       1023                   Sales   
1469   34      Travel_Rarely        628  Research & Development   

      DistanceFromHome  Education EducationField  EnvironmentSatisfaction  \
0                    1          2  Life Sciences                        2   
1                    8          1  Life Sciences                        3   
2                    2          2          Other                        4   
3                    3          4  Life Sciences                        4   
4                    2          1        Medical                        1   
...                ...        ...            ...                      ...   
1465                23          2        Medical                        3   
1466                 6          1        Medical                        4   
1467                 4          3  Life Sciences                        2   
1468                 2          3        Medical                        4   
1469                 8          3        Medical                        2   

      Gender  HourlyRate  ...  PerformanceRating  RelationshipSatisfaction  \
0     Female          94  ...                  3                         1   
1       Male          61  ...                  4                         4   
2       Male          92  ...                  3                         2   
3     Female          56  ...                  3                         3   
4       Male          40  ...                  3                         4   
...      ...         ...  ...                ...                       ...   
1465    Male          41  ...                  3                         3   
1466    Male          42  ...                  3                         1   
1467    Male          87  ...                  4                         2   
1468    Male          63  ...                  3                         4   
1469    Male          82  ...                  3                         1   

     StockOptionLevel  TotalWorkingYears TrainingTimesLastYear  \
0                   0                  8                     0   
1                   1                 10                     3   
2                   0                  7                     3   
3                   0                  8                     3   
4                   1                  6                     3   
...               ...                ...                   ...   
1465                1                 17                     3   
1466                1                  9                     5   
1467                1                  6                     0   
1468                0                 17                     3   
1469                0                  6                     3   

      WorkLifeBalance  YearsAtCompany  YearsInCurrentRole  \
0                   1               6                   4   
1                   3              10                   7   
2                   3               0                   0   
3                   3               8                   7   
4                   3               2                   2   
...               ...             ...                 ...   
1465                3               5                   2   
1466                3               7                   7 

In [8]:
len(df1)

1470

In [9]:
len(df1.columns)

30

In [10]:
df1['Gender'].replace({'Male':1,'Female':0}, inplace=True)

In [12]:
df1.head()

Age     BusinessTravel  DailyRate              Department  \
0   41      Travel_Rarely       1102                   Sales   
1   49  Travel_Frequently        279  Research & Development   
2   37      Travel_Rarely       1373  Research & Development   
3   33  Travel_Frequently       1392  Research & Development   
4   27      Travel_Rarely        591  Research & Development   

   DistanceFromHome  Education EducationField  EnvironmentSatisfaction  \
0                 1          2  Life Sciences                        2   
1                 8          1  Life Sciences                        3   
2                 2          2          Other                        4   
3                 3          4  Life Sciences                        4   
4                 2          1        Medical                        1   

   Gender  HourlyRate  ...  PerformanceRating  RelationshipSatisfaction  \
0       0          94  ...                  3                         1   
1       1          61  ...                  4                         4   
2       1          92  ...                  3                         2   
3       0          56  ...                  3                         3   
4       1          40  ...                  3                         4   

  StockOptionLevel  TotalWorkingYears TrainingTimesLastYear  WorkLifeBalance  \
0                0                  8                     0                1   
1                1                 10                     3                3   
2                0                  7                     3                3   
3                0                  8                     3                3   
4                1                  6                     3                3   

   YearsAtCompany  YearsInCurrentRole YearsSinceLastPromotion  \
0               6                   4                       0   
1              10                   7                       1   
2               0                   0                       0   
3               8                   7                       3   
4               2                   2                       2   

   YearsWithCurrManager  
0                     5  
1                     7  
2                     0  
3                     0  
4                     2  

[5 rows x 30 columns]

In [13]:
df1['PerformanceRating'].replace({3:1, 4:0}, inplace=True)

In [15]:
df1.head()

Age     BusinessTravel  DailyRate              Department  \
0   41      Travel_Rarely       1102                   Sales   
1   49  Travel_Frequently        279  Research & Development   
2   37      Travel_Rarely       1373  Research & Development   
3   33  Travel_Frequently       1392  Research & Development   
4   27      Travel_Rarely        591  Research & Development   

   DistanceFromHome  Education EducationField  EnvironmentSatisfaction  \
0                 1          2  Life Sciences                        2   
1                 8          1  Life Sciences                        3   
2                 2          2          Other                        4   
3                 3          4  Life Sciences                        4   
4                 2          1        Medical                        1   

   Gender  HourlyRate  ...  PerformanceRating  RelationshipSatisfaction  \
0       0          94  ...                  1                         1   
1       1          61  ...                  0                         4   
2       1          92  ...                  1                         2   
3       0          56  ...                  1                         3   
4       1          40  ...                  1                         4   

  StockOptionLevel  TotalWorkingYears TrainingTimesLastYear  WorkLifeBalance  \
0                0                  8                     0                1   
1                1                 10                     3                3   
2                0                  7                     3                3   
3                0                  8                     3                3   
4                1                  6                     3                3   

   YearsAtCompany  YearsInCurrentRole YearsSinceLastPromotion  \
0               6                   4                       0   
1              10                   7                       1   
2               0                   0                       0   
3               8                   7                       3   
4               2                   2                       2   

   YearsWithCurrManager  
0                     5  
1                     7  
2                     0  
3                     0  
4                     2  

[5 rows x 30 columns]

In [37]:
df1['OverTime'].replace({'Yes':1,'No':0}, inplace=True)

In [39]:
df1.OverTime

0       1
1       0
2       1
3       1
4       0
       ..
1465    0
1466    0
1467    1
1468    0
1469    0
Name: OverTime, Length: 1470, dtype: int64

### Get Dummmies

In [40]:
df2 = df1

In [41]:
len(df2.columns)

30

In [42]:
df2 = pd.get_dummies(df2, columns=['BusinessTravel','Department','Education','EducationField','EnvironmentSatisfaction','JobInvolvement','JobLevel','JobRole','JobSatisfaction','MaritalStatus','RelationshipSatisfaction','StockOptionLevel','TrainingTimesLastYear','WorkLifeBalance'])

In [43]:
df2.head()

Age  DailyRate  DistanceFromHome  Gender  HourlyRate  MonthlyIncome  \
0   41       1102                 1       0          94           5993   
1   49        279                 8       1          61           5130   
2   37       1373                 2       1          92           2090   
3   33       1392                 3       0          56           2909   
4   27        591                 2       1          40           3468   

   MonthlyRate  NumCompaniesWorked  OverTime  PercentSalaryHike  ...  \
0        19479                   8         1                 11  ...   
1        24907                   1         0                 23  ...   
2         2396                   6         1                 15  ...   
3        23159                   1         1                 11  ...   
4        16632                   9         0                 12  ...   

   TrainingTimesLastYear_1  TrainingTimesLastYear_2  TrainingTimesLastYear_3  \
0                        0                        0                        0   
1                        0                        0                        1   
2                        0                        0                        1   
3                        0                        0                        1   
4                        0                        0                        1   

   TrainingTimesLastYear_4  TrainingTimesLastYear_5  TrainingTimesLastYear_6  \
0                        0                        0                        0   
1                        0                        0                        0   
2                        0                        0                        0   
3                        0                        0                        0   
4                        0                        0                        0   

   WorkLifeBalance_1  WorkLifeBalance_2  WorkLifeBalance_3  WorkLifeBalance_4  
0                  1                  0                  0                  0  
1                  0                  0                  1                  0  
2                  0                  0                  1                  0  
3                  0                  0                  1                  0  
4                  0                  0                  1                  0  

[5 rows x 81 columns]

In [44]:
len(df2.columns)

81

### Model Training

In [45]:
df3 = df2

In [46]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 81 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Age                                1470 non-null   int64
 1   DailyRate                          1470 non-null   int64
 2   DistanceFromHome                   1470 non-null   int64
 3   Gender                             1470 non-null   int64
 4   HourlyRate                         1470 non-null   int64
 5   MonthlyIncome                      1470 non-null   int64
 6   MonthlyRate                        1470 non-null   int64
 7   NumCompaniesWorked                 1470 non-null   int64
 8   OverTime                           1470 non-null   int64
 9   PercentSalaryHike                  1470 non-null   int64
 10  PerformanceRating                  1470 non-null   int64
 11  TotalWorkingYears                  1470 non-null   int64
 12  YearsAtCompany      

In [47]:
x = df2

In [48]:
y = df['Attrition'].replace({'Yes':1,'No':0})

In [64]:
x_train,x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state = 10, stratify=y)

In [65]:
print(len(x_train),len(x_test), len(y_train), len(y_test))

1176 294 1176 294


### Random Forrest

In [66]:
rf_cl = RandomForestClassifier(random_state=30)
rf_cl

RandomForestClassifier(random_state=30)

In [67]:
rf_cl.fit(x_train, y_train)

RandomForestClassifier(random_state=30)

## Evaluation

In [68]:
def evaluation(string , model, ind_var, act):
    print(string.center(50,'*'))
    
    pred = model.predict(ind_var)
    cnf_matrix = confusion_matrix(act,pred)
    print('confusion matrix ',cnf_matrix)
    
    accuracy = accuracy_score(act,pred)
    print('Accuracy : ', accuracy)

    clf_report = classification_report(act,pred)
    print('Classification report:\n',clf_report)
    
evaluation('Test Data Evaluation ', rf_cl, x_test, y_test)
print('#'*50)
evaluation('Train Data Evauation ', rf_cl, x_train, y_train)

**************Test Data Evaluation ***************
confusion matrix  [[247   0]
 [ 40   7]]
Accuracy :  0.8639455782312925
Classification report:
               precision    recall  f1-score   support

           0       0.86      1.00      0.93       247
           1       1.00      0.15      0.26        47

    accuracy                           0.86       294
   macro avg       0.93      0.57      0.59       294
weighted avg       0.88      0.86      0.82       294

##################################################
**************Train Data Evauation ***************
confusion matrix  [[986   0]
 [  0 190]]
Accuracy :  1.0
Classification report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00       986
           1       1.00      1.00      1.00       190

    accuracy                           1.00      1176
   macro avg       1.00      1.00      1.00      1176
weighted avg       1.00      1.00      1.00      1176



### Logistic

In [70]:
from sklearn.linear_model import LogisticRegression

In [71]:
log_cl = LogisticRegression()
log_cl.fit(x_train,y_train)

LogisticRegression()

In [72]:
def evaluation(string , model, ind_var, act):
    print(string.center(50,'*'))
    
    pred = model.predict(ind_var)
    cnf_matrix = confusion_matrix(act,pred)
    print('confusion matrix ',cnf_matrix)
    
    accuracy = accuracy_score(act,pred)
    print('Accuracy : ', accuracy)

    clf_report = classification_report(act,pred)
    print('Classification report:\n',clf_report)
    
evaluation('Test Data Evaluation ', log_cl, x_test, y_test)
print('#'*50)
evaluation('Train Data Evauation ', log_cl, x_train, y_train)

**************Test Data Evaluation ***************
confusion matrix  [[247   0]
 [ 47   0]]
Accuracy :  0.8401360544217688
Classification report:
               precision    recall  f1-score   support

           0       0.84      1.00      0.91       247
           1       0.00      0.00      0.00        47

    accuracy                           0.84       294
   macro avg       0.42      0.50      0.46       294
weighted avg       0.71      0.84      0.77       294

##################################################
**************Train Data Evauation ***************
confusion matrix  [[983   3]
 [184   6]]
Accuracy :  0.8409863945578231
Classification report:
               precision    recall  f1-score   support

           0       0.84      1.00      0.91       986
           1       0.67      0.03      0.06       190

    accuracy                           0.84      1176
   macro avg       0.75      0.51      0.49      1176
weighted avg       0.81      0.84      0.78      1176



### KNN classifier

In [73]:
from sklearn.neighbors import KNeighborsClassifier

In [76]:
from sklearn.metrics import accuracy_score

In [75]:
knn_cl = KNeighborsClassifier(n_neighbors=7, p=1)
knn_cl.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=7, p=1)

In [77]:
def evaluation(string,model, ind_var,y_act):
    print(string.center(50, '*'))
    
    pred = model.predict(ind_var)
    
    cnf_matrix = confusion_matrix(y_act, pred)
    print('Confusion Matrix :\n', cnf_matrix)
    
    print('**'*25)
    acc_score = accuracy_score(y_act, pred)
    print('Accuracy is :', acc_score)
    print('**'*25)
    
    clf_report = classification_report(y_act, pred)
    print('Classification Report :\n', clf_report)
    
evaluation('Test Data Evaluation', knn_cl, x_test, y_test)

***************Test Data Evaluation***************
Confusion Matrix :
 [[242   5]
 [ 43   4]]
**************************************************
Accuracy is : 0.8367346938775511
**************************************************
Classification Report :
               precision    recall  f1-score   support

           0       0.85      0.98      0.91       247
           1       0.44      0.09      0.14        47

    accuracy                           0.84       294
   macro avg       0.65      0.53      0.53       294
weighted avg       0.78      0.84      0.79       294



### Decision Tree

In [78]:
from sklearn.tree import DecisionTreeClassifier, plot_tree

In [83]:
dt_cl = DecisionTreeClassifier(random_state=30 , criterion='entropy')
dt_cl.fit(x_train,y_train)

DecisionTreeClassifier(criterion='entropy', random_state=30)

In [84]:
def evaluation(string, model, ind_var, act):
    string.center(50, '*')
    
    pred = model.predict(ind_var)
    cnf_matrix = confusion_matrix(act, pred)
    print('Confusion Matrix :\n', cnf_matrix)
    
    accuracy = accuracy_score(act, pred)
    print('Accuracy is :' ,accuracy)
    
    clf_report = classification_report(act, pred)
    print('Classification Report :\n', clf_report)
    
    return cnf_matrix
    
evaluation('Test Data Evaluation', dt_cl, x_test, y_test)

Confusion Matrix :
 [[211  36]
 [ 29  18]]
Accuracy is : 0.7789115646258503
Classification Report :
               precision    recall  f1-score   support

           0       0.88      0.85      0.87       247
           1       0.33      0.38      0.36        47

    accuracy                           0.78       294
   macro avg       0.61      0.62      0.61       294
weighted avg       0.79      0.78      0.78       294



array([[211,  36],
       [ 29,  18]], dtype=int64)

In [86]:
cnf_matrix = evaluation('Train Data Evaluation', dt_cl, x_train, y_train)
cnf_matrix

Confusion Matrix :
 [[986   0]
 [  0 190]]
Accuracy is : 1.0
Classification Report :
               precision    recall  f1-score   support

           0       1.00      1.00      1.00       986
           1       1.00      1.00      1.00       190

    accuracy                           1.00      1176
   macro avg       1.00      1.00      1.00      1176
weighted avg       1.00      1.00      1.00      1176



array([[986,   0],
       [  0, 190]], dtype=int64)